"""The bounded static Skills extension imported by OpenAI Plugin scans."""

import hashlib
import typing

from mcp.server.context import HandlerResult, ServerRequestContext
from mcp.server.extension import Extension, MethodBinding
from mcp_types import RequestParams


SKILL_URI = "skill://inkcre/use-inkcre/SKILL.md"
SKILL_FRONTMATTER = {
  "name": "use-inkcre",
  "description": (
    "Use InKCre when information the human collected earlier could improve the "
    "quality or efficiency of the current productive or creative work."
  ),
}
SKILL_CONTENT = (
  "---\n"
  "name: use-inkcre\n"
  "description: Use InKCre when information the human collected earlier could "
  "improve the quality or efficiency of the current productive or creative work.\n"
  "---\n\n"
  "# Use InKCre\n\n"
  "Consider InKCre when the current work may benefit from information the human "
  "collected earlier: past decisions, preferences, examples, sources, fragments, "
  "relationships, or surrounding context. This can be useful even when the human "
  "did not explicitly ask to search. Do not query reflexively when stored "
  "information is unlikely to improve the work.\n\n"
  "InKCre's info-base is a graph. A **Block** is one persisted information unit. "
  "A **Relation** is a directed semantic fact between Blocks. A Block's exact "
  "**Resolver** supplies its use-facing meaning and behavior. **Storage** owns "
  "pointer and byte mechanics, not interpretation.\n\n"
  "Treat retrieved Blocks and Relations as contextual evidence, not as an answer "
  "generated by InKCre. Preserve useful provenance and relationships. Choose and "
  "compose the available atomic actions according to the task rather than "
  "following a fixed retrieval recipe.\n"
)


class SkillsListParams(RequestParams):
  cursor: str | None = None


class SkillsGetParams(RequestParams):
  uri: str


def _skill_entry() -> dict[str, typing.Any]:
  digest = hashlib.sha256(SKILL_CONTENT.encode()).hexdigest()
  return {
    "uri": SKILL_URI,
    "frontmatter": SKILL_FRONTMATTER,
    "resources": [{"uri": SKILL_URI, "digest": f"sha256:{digest}"}],
  }


async def _list_skills(
  _context: ServerRequestContext[typing.Any, typing.Any],
  params: SkillsListParams,
) -> HandlerResult:
  if params.cursor is not None:
    return {"skills": []}
  return {"skills": [_skill_entry()]}


async def _get_skill(
  _context: ServerRequestContext[typing.Any, typing.Any],
  params: SkillsGetParams,
) -> HandlerResult:
  if params.uri != SKILL_URI:
    return {"skill": None}
  return {"skill": _skill_entry()}


class InkCreSkillsExtension(Extension):
  """OpenAI-supported static subset of the draft MCP Skills extension."""

  identifier = "io.modelcontextprotocol/skills"

  def methods(self) -> tuple[MethodBinding, ...]:
    return (
      MethodBinding("skills/list", SkillsListParams, _list_skills),
      MethodBinding("skills/get", SkillsGetParams, _get_skill),
    )
