# syntax=docker/dockerfile:1

FROM postgrest/postgrest:v14.15@sha256:2f8e7b656f09db697a8875177694b417b35cb76c21370de07fc54e711e902326

ARG SOURCE_REVISION=unknown
LABEL org.opencontainers.image.revision="${SOURCE_REVISION}"

COPY --chmod=755 scripts/postgrest-entrypoint.sh /usr/local/bin/inkcre-postgrest

ENTRYPOINT ["/usr/local/bin/inkcre-postgrest"]
