"""Canonical AI contracts and shared persistence models."""

from .capability import (
  AICapability,
  AICapabilityType,
  AIFeature,
  AIModality,
  AIModelCapability,
  ChatCapability,
  EmbeddingCapability,
  normalize_capabilities,
)
from .chat import (
  AudioContentPart,
  AssistantMessage,
  FunctionTool,
  ImageContentPart,
  JSONValue,
  Message,
  NamedToolChoice,
  SystemMessage,
  TextContentPart,
  ToolCall,
  ToolChoice,
  ToolResult,
  ToolResultMessage,
  UserContentPart,
  UserMessage,
  VideoContentPart,
  validate_message_history,
)
from .embedding import BlockEmbeddingModel, RelationEmbeddingModel
from .main import (
  AIDialectID,
  AIDialectModel,
  AIModelID,
  AIModelModel,
  AIProviderID,
  AIProviderModel,
  EmbeddingProfileID,
  EmbeddingProfileModel,
)

__all__ = [
  "AICapability",
  "AICapabilityType",
  "AIDialectID",
  "AIDialectModel",
  "AIFeature",
  "AIModality",
  "AIModelCapability",
  "AIModelID",
  "AIModelModel",
  "AIProviderID",
  "AIProviderModel",
  "AudioContentPart",
  "AssistantMessage",
  "BlockEmbeddingModel",
  "ChatCapability",
  "EmbeddingCapability",
  "EmbeddingProfileID",
  "EmbeddingProfileModel",
  "FunctionTool",
  "ImageContentPart",
  "JSONValue",
  "Message",
  "NamedToolChoice",
  "RelationEmbeddingModel",
  "SystemMessage",
  "TextContentPart",
  "ToolCall",
  "ToolChoice",
  "ToolResult",
  "ToolResultMessage",
  "UserContentPart",
  "UserMessage",
  "VideoContentPart",
  "normalize_capabilities",
  "validate_message_history",
]
