"""embeddings cascade

Revision ID: 034e741f97a2
Revises: 23257a559f94
Create Date: 2025-09-18 19:00:57.545345

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "034e741f97a2"
down_revision: Union[str, Sequence[str], None] = "23257a559f94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("block_embeddings_id_fkey"), "block_embeddings", type_="foreignkey")
    op.create_foreign_key(
        None, "block_embeddings", "blocks", ["id"], ["id"], onupdate="CASCADE", ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("relation_embeddings_id_fkey"), "relation_embeddings", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "relation_embeddings",
        "relations",
        ["id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "relation_embeddings", type_="foreignkey")
    op.create_foreign_key(
        op.f("relation_embeddings_id_fkey"), "relation_embeddings", "relations", ["id"], ["id"]
    )
    op.drop_constraint(None, "block_embeddings", type_="foreignkey")
    op.create_foreign_key(
        op.f("block_embeddings_id_fkey"), "block_embeddings", "blocks", ["id"], ["id"]
    )
    # ### end Alembic commands ###
