"""add_config_schema_and_source_state_remove_extension_state

Revision ID: 2e3c2423b46a
Revises: 377f9730730e
Create Date: 2025-12-14 15:05:34.352489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e3c2423b46a'
down_revision: Union[str, Sequence[str], None] = '377f9730730e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extensions', sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('extensions', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('sources', sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Migrate extension state to source state
    # Note: This assumes each extension has at most one source that uses state
    # Manual migration may be needed for extensions with multiple sources
    connection = op.get_bind()
    
    # Get all extensions with state
    extensions_with_state = connection.execute(
        sa.text("SELECT id, state FROM extensions WHERE state IS NOT NULL")
    ).fetchall()
    
    for ext_id, ext_state in extensions_with_state:
        # Find sources for this extension (by type pattern)
        sources = connection.execute(
            sa.text("SELECT id FROM sources WHERE type LIKE :pattern"),
            {"pattern": f"extensions.{ext_id}.%"}
        ).fetchall()
        
        if sources:
            # Migrate state to the first source found
            # If there are multiple sources, only the first gets the state
            source_id = sources[0][0]
            connection.execute(
                sa.text("UPDATE sources SET state = :state WHERE id = :id"),
                {"state": ext_state, "id": source_id}
            )
    
    # Now drop the extension state column
    op.drop_column('extensions', 'state')
    
    op.alter_column('sources_collect_jobs', 'state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('sources_collect_jobs', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources_collect_jobs', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('sources_collect_jobs', 'state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('sources', 'state')
    op.add_column('extensions', sa.Column('state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('extensions', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('extensions', 'config_schema')
    # ### end Alembic commands ###
