"""add_job_submission_trace_context

Revision ID: 3d9593b0c855
Revises: a0465e3b028f
Create Date: 2026-10-03 17:23:07.957043

"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3d9593b0c855"
down_revision: str | Sequence[str] | None = "a0465e3b028f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "jobs", sa.Column("submission_traceparent", sa.Text(), nullable=True), schema="inkcre"
  )
  op.add_column(
    "jobs", sa.Column("submission_tracestate", sa.Text(), nullable=True), schema="inkcre"
  )
  op.create_check_constraint(
    "jobs_submission_traceparent_capacity",
    "jobs",
    "octet_length(submission_traceparent) <= 512",
    schema="inkcre",
  )
  op.create_check_constraint(
    "jobs_submission_tracestate_capacity",
    "jobs",
    "octet_length(submission_tracestate) <= 512",
    schema="inkcre",
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint(
    "jobs_submission_tracestate_capacity", "jobs", schema="inkcre", type_="check"
  )
  op.drop_constraint(
    "jobs_submission_traceparent_capacity", "jobs", schema="inkcre", type_="check"
  )
  op.drop_column("jobs", "submission_tracestate", schema="inkcre")
  op.drop_column("jobs", "submission_traceparent", schema="inkcre")
  # ### end Alembic commands ###
