"""embeddings add updated_At

Revision ID: 671679032964
Revises: 034e741f97a2
Create Date: 2025-09-18 21:06:52.180438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671679032964'
down_revision: Union[str, Sequence[str], None] = '034e741f97a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_embeddings', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('relation_embeddings', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relation_embeddings', 'updated_at')
    op.drop_column('block_embeddings', 'updated_at')
    # ### end Alembic commands ###
