"""add sources_collect_jobs table

Revision ID: 74117f65de1f
Revises: 2d5747ad2f07
Create Date: 2025-12-11 20:41:19.090440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74117f65de1f'
down_revision: Union[str, Sequence[str], None] = '2d5747ad2f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources_collect_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'FINISHED', 'FAILED', name='sourcecollectjobstatus'), nullable=False),
    sa.Column('state', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source'], ['sources.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources_collect_jobs')
    # ### end Alembic commands ###
