"""init

Revision ID: e5a01f9e69ef
Revises:
Create Date: 2025-12-27 21:22:28.578426

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.schemas.source.main
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = "e5a01f9e69ef"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # Install extensions
  op.execute("CREATE EXTENSION IF NOT EXISTS vector;")

  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "extensions",
    sa.Column("id", sa.TEXT, nullable=False),
    sa.Column("version", sa.Text(), nullable=False),
    sa.Column("disabled", sa.Boolean(), nullable=False),
    sa.Column("nickname", sa.TEXT, nullable=True),
    sa.Column(
      "config",
      postgresql.JSONB(astext_type=sa.Text()),
      server_default=sa.text("'{}'::jsonb"),
      nullable=True,
    ),
    sa.Column("config_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "logs",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column(
      "timestamp",
      sa.TIMESTAMP(timezone=True),
      server_default=sa.text("CURRENT_TIMESTAMP"),
      nullable=True,
    ),
    sa.Column("severity_number", sa.SmallInteger(), nullable=False),
    sa.Column("severity_text", sa.TEXT, nullable=False),
    sa.Column("body", sa.TEXT, nullable=False),
    sa.Column("trace_id", sa.TEXT, nullable=True),
    sa.Column("span_id", sa.TEXT, nullable=True),
    sa.Column(
      "attributes",
      postgresql.JSONB(astext_type=sa.Text()),
      server_default=sa.text("'{}'::jsonb"),
      nullable=False,
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "sources_types",
    sa.Column("id", sa.Text(), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column(
      "config_schema",
      postgresql.JSONB(astext_type=sa.Text()),
      server_default=sa.text("'{}'::jsonb"),
      nullable=True,
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "storage_types",
    sa.Column("id", sa.Text(), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column(
      "config_schema",
      postgresql.JSONB(astext_type=sa.Text()),
      server_default=sa.text("'{}'::jsonb"),
      nullable=True,
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "sources",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("type", sa.Text(), nullable=True),
    sa.Column("nickname", sa.TEXT, nullable=True),
    sa.Column(
      "config",
      postgresql.JSONB(astext_type=sa.Text()),
      server_default=sa.text("'{}'::jsonb"),
      nullable=True,
    ),
    sa.Column(
      "collect_at",
      app.schemas.source.main.CollectAtType(astext_type=sa.Text()),
      nullable=True,
    ),
    sa.Column(
      "state",
      postgresql.JSONB(astext_type=sa.Text()),
      server_default=sa.text("'{}'::jsonb"),
      nullable=True,
    ),
    sa.ForeignKeyConstraint(
      ["type"], ["sources_types.id"], onupdate="CASCADE", ondelete="CASCADE"
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "storages",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("type", sa.Text(), nullable=True),
    sa.Column("nickname", sa.TEXT, nullable=True),
    sa.Column(
      "config",
      postgresql.JSONB(astext_type=sa.Text()),
      server_default=sa.text("'{}'::jsonb"),
      nullable=True,
    ),
    sa.ForeignKeyConstraint(
      ["type"], ["storage_types.id"], onupdate="CASCADE", ondelete="CASCADE"
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "blocks",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column(
      "created_at",
      sa.TIMESTAMP(timezone=True),
      server_default=sa.text("CURRENT_TIMESTAMP"),
      nullable=True,
    ),
    sa.Column(
      "updated_at",
      sa.TIMESTAMP(timezone=True),
      server_default=sa.text("CURRENT_TIMESTAMP"),
      nullable=True,
    ),
    sa.Column("storage", sa.Integer(), nullable=True),
    sa.Column("resolver", sa.Text(), nullable=False),
    sa.Column("content", sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(
      ["storage"], ["storages.id"], onupdate="CASCADE", ondelete="SET NULL"
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "sources_collect_jobs",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("source", sa.Integer(), nullable=True),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column("closed_at", sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column(
      "status",
      sa.Enum("pending", "running", "finished", "failed", name="sourcecollectjobstatus"),
      server_default="pending",
      nullable=True,
    ),
    sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(
      ["source"], ["sources.id"], onupdate="CASCADE", ondelete="CASCADE"
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "block_embeddings",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["id"], ["blocks.id"], onupdate="CASCADE", ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "relations",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column(
      "updated_at",
      sa.TIMESTAMP(timezone=True),
      server_default=sa.text("CURRENT_TIMESTAMP"),
      nullable=True,
    ),
    sa.Column("from_", sa.Integer(), nullable=True),
    sa.Column("to_", sa.Integer(), nullable=True),
    sa.Column("content", sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(
      ["from_"], ["blocks.id"], onupdate="CASCADE", ondelete="CASCADE"
    ),
    sa.ForeignKeyConstraint(["to_"], ["blocks.id"], onupdate="CASCADE", ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "relation_embeddings",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(
      ["id"], ["relations.id"], onupdate="CASCADE", ondelete="CASCADE"
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  # ### end Alembic commands ###

  # Create role and grant for PostgREST
  op.execute("CREATE ROLE authenticated NOLOGIN NOINHERIT;")
  op.execute("GRANT authenticated TO postgres;")
  op.execute("GRANT SELECT ON public.sources_types TO authenticated;")
  op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON public.sources TO authenticated;")
  op.execute("GRANT SELECT, INSERT ON public.sources_collect_jobs TO authenticated;")
  op.execute("GRANT SELECT ON public.extensions TO authenticated;")
  op.execute("GRANT SELECT ON public.logs TO authenticated;")
  op.execute(
    "GRANT SELECT ON public.blocks, public.relations, public.storages, public.storage_types TO authenticated;"
  )
  op.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;")


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("relation_embeddings")
  op.drop_table("relations")
  op.drop_table("block_embeddings")
  op.drop_table("sources_collect_jobs")
  op.drop_table("blocks")
  op.drop_table("storages")
  op.drop_table("sources")
  op.drop_table("storage_types")
  op.drop_table("sources_types")
  op.drop_table("logs")
  op.drop_table("extensions")
  # ### end Alembic commands ###
